#!/usr/bin/env perl
use Modern::Perl;

use Getopt::Lazy
    'username=s'     => 'Login name                 (required)',
    'compname=s'     => 'Competition name           (required)',
    -summary => 'Add a user to a competition',
    -usage => '%c %o',
    ;

use Tipping::Schema ();

GetOptions(-autohelp => sub {
        not (defined $username and defined $compname)
    });

my $schema = Tipping::Schema->connect;
$schema->resultset('User')->find({ username => $username})
                          ->add_to_competitions({ name => $compname });
