#!/usr/bin/env perl
use Modern::Perl;

use Getopt::Lazy
    'name=s' => 'Name of competition (required)',
    'password=s' => 'Password to join competition (optional)',
    -summary => 'Add a tipping competition',
    -usage => '%c %o',
    ;

use Tipping::Schema ();

GetOptions(-autohelp => sub { not defined $name });

my $schema = Tipping::Schema->instance;
$schema->resultset('Competition')->create({
        name        => $name,
        password    => $password,
    });
