#!/bin/bash

#set -e

# First up, reset/create the database

if grep -q dbi:SQLite tipping.yml; then

    rm -f sqlite.db

elif grep -q dbi:Pg tipping.yml; then

    export PGUSER=tipping
    export PGPASSWORD=tipping
    dropdb -h localhost tipping
    createdb -h localhost -E utf8 tipping
    #psql -h localhost tipping "ALTER USER tipping SET Client_min_messages='warning'"

elif grep -q dbi:mysql tipping.yml; then

    mysqladmin -f -u tipping --password=tipping drop tipping
    mysqladmin -u tipping --password=tipping create tipping

else
    echo Cannot determine database
    exit 1
fi

# Deploy the schema
./script/tipping_db_update.pl

create_user() {
    local i=$1
    ./devscripts/create-user --username user$i --password pass$i --email user$i@nftatips.org --realname "User $i"
}

# Now add some extra stuff
for c in `seq -f '%02.f' 1 2`; do
    ./devscripts/create-competition --name comp$c
done
for u in `seq -f '%02.f' 1 4`; do
    create_user $u
    for c in `seq -f '%02.f' 1 2`; do
        ./devscripts/add-user-to-competition --username user$u --compname comp$c
        for r in `seq 1 4`; do
            for t in Hawthorn Essendon Richmond Melbourne Collingwood Sydney Brisbane Fremantle; do
                ./devscripts/enter-tip --username user$u --compname comp$c \
                                       --round $r --team $t
                echo ./devscripts/enter-tip --username user$u --compname comp$c \
                                       --round $r --team $t
            done
        done
    done
done
